/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChucNang;

import ConnectToSql.Database;
import Models.TTLuong;
import Models.TTNhanVien;
import Models.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.util.List;

/**
 *
 * @author Admin
 */
public class timkiemluong extends javax.swing.JFrame {
    timkiemluongdao dao = new timkiemluongdao();
    String StrFindmaluong = "";
    String StrId = "";
    Database dt = new Database();
    Connection conn = null;
    PreparedStatement pst = null; 
    /**
     * Creates new form timkiemluong
     */
    public timkiemluong() {
        initComponents();
        setLocationRelativeTo(null);
       show_TTL();
      // show_TTL1();
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        machucvu = new javax.swing.JRadioButton();
        maluong = new javax.swing.JRadioButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtimkiemxx = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setName("Thông Tin"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Thông Tin Tìm Kiếm :");

        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        btntimkiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/tim.png"))); // NOI18N
        btntimkiem.setText("Tìm Kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        machucvu.setBackground(new java.awt.Color(204, 255, 255));
        machucvu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        machucvu.setText("Mã Chức Vụ");
        machucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machucvuActionPerformed(evt);
            }
        });

        maluong.setBackground(new java.awt.Color(204, 255, 255));
        maluong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maluong.setText("Mã Lương");
        maluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maluongActionPerformed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/close1.png"))); // NOI18N
        exit.setText("Thoát");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/KhenThuong.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maluong, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(machucvu))
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(machucvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        tbtimkiemxx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Lương", "Mã Chức Vụ", "LCB", "PCChuc Vu", "Ngay Nhap", "LCBMoi", "Ngày Sửa", "Lý Do", "PCVuMoi", "Ngày Sửa PC", "Ghi Chu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbtimkiemxx);
        if (tbtimkiemxx.getColumnModel().getColumnCount() > 0) {
            tbtimkiemxx.getColumnModel().getColumn(0).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(1).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(2).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(3).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(4).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(5).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(6).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(7).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(8).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(9).setResizable(false);
            tbtimkiemxx.getColumnModel().getColumn(10).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  




    public void show_TTL(){
        timkiemluongdao dao = new timkiemluongdao();
        
        DefaultTableModel model = (DefaultTableModel)tbtimkiemxx.getModel();
        model.setRowCount(0);
        for(TTLuong o : dao.timkiemmaluong(StrFindmaluong)){
            model.addRow(new Object[]{o.getMaLuong(), o.getMaChucVu(), o.getLCB(),  o.getPCChucVu(), o.getNgayNhap(), o.getLCBMoi(), o.getNgaySua(), o.getPCCVuMoi(), o.getNgaySuaPC(), o.getLyDo(), o.getGhiChu()});                      
        }       
    }
    public void show_TTL1(){
        timkiemluongdao dao = new timkiemluongdao();
        DefaultTableModel model = (DefaultTableModel)tbtimkiemxx.getModel();
        model.setRowCount(0);
        for(TTLuong o : dao.timkiemmachucvu(StrId)){
            model.addRow(new Object[]{o.getMaLuong(), o.getMaChucVu(), o.getLCB(),  o.getPCChucVu(), o.getNgayNhap(), o.getLCBMoi(), o.getNgaySua(), o.getPCCVuMoi(), o.getNgaySuaPC(), o.getLyDo(), o.getGhiChu()});                      
        }       
    }
    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
        //           StrFind = txttimkiem.getText();
        //           Filltable();  if (i == 1)
        {
                    StrFindmaluong = txttimkiem.getText();
                    show_TTL();
        }
        if (i == 2)
        {
                    StrId = txttimkiem.getText();
                    show_TTL();
        }
    }//GEN-LAST:event_txttimkiemActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        if (i == 1)
        {
                    StrFindmaluong = txttimkiem.getText();
                    show_TTL();
        }
        if (i == 2)
        {
                    StrId = txttimkiem.getText();
                    show_TTL1();
        }
                   

    }//GEN-LAST:event_btntimkiemActionPerformed
     
    int i =0;
    private void machucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machucvuActionPerformed
        // TODO add your handling code here:
        i = 2;
    }//GEN-LAST:event_machucvuActionPerformed

    private void maluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maluongActionPerformed
        // TODO add your handling code here:
        i = 1;
    }//GEN-LAST:event_maluongActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
       

        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timkiemluong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timkiemluong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timkiemluong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timkiemluong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timkiemluong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton machucvu;
    private javax.swing.JRadioButton maluong;
    private javax.swing.JTable tbtimkiemxx;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
