/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChucNang;

import Models.*;
import TaiKhoan.DangKy;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TimKiem extends javax.swing.JFrame {
  TimKiemDao dao = new TimKiemDao();
  String StrFind = "";
  String StrId = "";
    /**
     * Creates new form TimKiem
     */
    public TimKiem() {
        initComponents();
         Filltable();
         

    }
    public void Filltable(){
        DefaultTableModel tbModel = (DefaultTableModel) tbtimkiem.getModel();
        tbModel.setRowCount(0);
       for(TTNhanVien o : dao.timkiemname(StrFind)){
           // tbModel.addRow(new Object[]{o.getMaNV(), o.getHoTen(), o.getNgaySinh(), o.getGioiTinh(), o.getMaHopDong(), o.getMaPhongBan(), o.getMaBoPhan(), o.getMaChucVu(), o.getTTHonNhan(), o.getAnh(), o.getGhiChu()});   
                Object dataRow[] = new Object[11];
                dataRow[0] = o.getMaNV();
                dataRow[1] = o.getHoTen();
                dataRow[2] = o.getNgaySinh();
                dataRow[3] = o.getGioiTinh();
                dataRow[4] = o.getMaChucVu();
                dataRow[5] = o.getMaHopDong();
                dataRow[6] = o.getMaPhongBan();
                dataRow[7] = o.getMaBoPhan();
                dataRow[8] = o.getTTHonNhan();
                dataRow[9] = o.getAnh();
                dataRow[10] = o.getGhiChu();
                tbModel.addRow(dataRow);
                
                
          }
    }
    public void Filltable1(){
        DefaultTableModel tbModel = (DefaultTableModel) tbtimkiem.getModel();
        tbModel.setRowCount(0);
       for(TTNhanVien o : dao.timkiemid(StrId)){
           // tbModel.addRow(new Object[]{o.getMaNV(), o.getHoTen(), o.getNgaySinh(), o.getGioiTinh(), o.getMaHopDong(), o.getMaPhongBan(), o.getMaBoPhan(), o.getMaChucVu(), o.getTTHonNhan(), o.getAnh(), o.getGhiChu()});   
                Object dataRow[] = new Object[11];
                dataRow[0] = o.getMaNV();
                dataRow[1] = o.getHoTen();
                dataRow[2] = o.getNgaySinh();
                dataRow[3] = o.getGioiTinh();
                dataRow[4] = o.getMaChucVu();
                dataRow[5] = o.getMaHopDong();
                dataRow[6] = o.getMaPhongBan();
                dataRow[7] = o.getMaBoPhan();
                dataRow[8] = o.getTTHonNhan();
                dataRow[9] = o.getAnh();
                dataRow[10] = o.getGhiChu();
                tbModel.addRow(dataRow);
                
                
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        hoten = new javax.swing.JRadioButton();
        ID = new javax.swing.JRadioButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtimkiem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setName("Thông Tin"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Thông Tin Tìm Kiếm :");

        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        btntimkiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/tim.png"))); // NOI18N
        btntimkiem.setText("Tìm Kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        hoten.setBackground(new java.awt.Color(255, 255, 204));
        hoten.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hoten.setText("Họ Và Tên");
        hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotenActionPerformed(evt);
            }
        });

        ID.setBackground(new java.awt.Color(255, 255, 204));
        ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ID.setText("ID");
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/exiit.png"))); // NOI18N
        exit.setText("Thoát");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/timkiem.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(hoten)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btntimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbtimkiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Và Tên", "Ngày Sinh", "Giới Tính", "Mã Chức Vụ", "Mã Hợp Đồng", "Mã Phòng Ban", "Mã Bộ Phận", "TT Hôn Nhân", "Ảnh", "Ghi Chu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbtimkiem);
        if (tbtimkiem.getColumnModel().getColumnCount() > 0) {
            tbtimkiem.getColumnModel().getColumn(0).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(1).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(2).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(3).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(4).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(5).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(6).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(7).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(8).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(9).setResizable(false);
            tbtimkiem.getColumnModel().getColumn(10).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
               if (i == 1)
                {
                     StrFind = txttimkiem.getText();
                     Filltable();
                }
                if (i == 2)
                {
                     StrId = txttimkiem.getText();
                     Filltable1();
               
               }
        
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
//           StrFind = txttimkiem.getText();
//           Filltable();
               if (i == 1)
                {
                     StrFind = txttimkiem.getText();
                     Filltable();
                }
                if (i == 2)
                {
                     StrId = txttimkiem.getText();
                     Filltable1();
                }
             
          
    }//GEN-LAST:event_txttimkiemActionPerformed
        int i = 0;
    private void hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotenActionPerformed
        // TODO add your handling code here:
         i = 1;
    }//GEN-LAST:event_hotenActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
        i = 2;
    }//GEN-LAST:event_IDActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         TimKiem dk = new TimKiem();
        dk.dispose();
      
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TimKiem().setVisible(true);
               TimKiem tk  = new TimKiem();
               tk.setLocationRelativeTo(null);
               tk.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ID;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton hoten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtimkiem;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
