/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import ChucNang.DanhGia;
import TaiKhoan.*;
import ChucNang.*;
import DanhMuc.*;
import Models.Share;
import QuanLy.*;
/**
 *
 * @author USER
 */
public class coban3 extends javax.swing.JFrame {

    /**
     * Creates new form coban
     */
    public coban3() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jluong = new javax.swing.JRadioButton();
        jttnhanvien = new javax.swing.JRadioButton();
        jnhans = new javax.swing.JRadioButton();
        jhoso1 = new javax.swing.JRadioButton();
        txttimkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu25 = new javax.swing.JMenu();
        jdangnhap = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jdangky = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jexit = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jdanhmuc = new javax.swing.JMenu();
        jnhansu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        txtluong = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        quyenloi = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        ttcn = new javax.swing.JMenuItem();
        jquanly = new javax.swing.JMenu();
        bangcong = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jbophan = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jhoso = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jphongban = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        danhgia = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("jRadioButtonMenuItem4");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("jRadioButtonMenuItem5");

        jMenu1.setText("jMenu1");

        jRadioButtonMenuItem6.setSelected(true);
        jRadioButtonMenuItem6.setText("jRadioButtonMenuItem6");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem7.setSelected(true);
        jRadioButtonMenuItem7.setText("jRadioButtonMenuItem7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem2.setText("jMenuItem2");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Nhân Sự", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(153, 0, 204))); // NOI18N
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/cuong.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Nhanh", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jluong.setBackground(new java.awt.Color(255, 255, 255));
        jluong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jluong.setText("Lương");
        jluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jluongActionPerformed(evt);
            }
        });

        jttnhanvien.setBackground(new java.awt.Color(255, 255, 255));
        jttnhanvien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jttnhanvien.setText("TT Nhân Viên");
        jttnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttnhanvienActionPerformed(evt);
            }
        });

        jnhans.setBackground(new java.awt.Color(255, 255, 255));
        jnhans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jnhans.setText("Nhân Sự");
        jnhans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnhansActionPerformed(evt);
            }
        });

        jhoso1.setBackground(new java.awt.Color(255, 255, 255));
        jhoso1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jhoso1.setText("Hồ Sơ");
        jhoso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhoso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jttnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(jhoso1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jluong, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jnhans, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnhans)
                    .addComponent(jluong))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jttnhanvien)
                    .addComponent(jhoso1))
                .addGap(15, 15, 15))
        );

        txttimkiem.setBackground(new java.awt.Color(255, 255, 255));
        txttimkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/tim.png"))); // NOI18N
        txttimkiem.setText("Tìm Kiếm");
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/162422041_290274995954082_1096507565071897479_n (2).png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/179533925_921342598704810_3222153744781631452_n.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jMenu25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/administrator.png"))); // NOI18N
        jMenu25.setText("Tài Khoản");

        jdangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/dangnhap.png"))); // NOI18N
        jdangnhap.setText("Đăng Nhập");
        jMenu25.add(jdangnhap);
        jMenu25.add(jSeparator4);

        jdangky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/dangki.png"))); // NOI18N
        jdangky.setText("Đăng Kí");
        jdangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdangkyActionPerformed(evt);
            }
        });
        jMenu25.add(jdangky);
        jMenu25.add(jSeparator5);

        jexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/exiit.png"))); // NOI18N
        jexit.setText("Thoát");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        jMenu25.add(jexit);
        jMenu25.add(jSeparator11);

        jMenuBar1.add(jMenu25);

        jdanhmuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/Danh_muc.png"))); // NOI18N
        jdanhmuc.setText("Danh Mục");

        jnhansu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/eee.png"))); // NOI18N
        jnhansu.setText("Nhân Sự");
        jnhansu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnhansuActionPerformed(evt);
            }
        });
        jdanhmuc.add(jnhansu);
        jdanhmuc.add(jSeparator1);

        txtluong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/TinhLuong.png"))); // NOI18N
        txtluong.setText("Lương");
        txtluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtluongActionPerformed(evt);
            }
        });
        jdanhmuc.add(txtluong);
        jdanhmuc.add(jSeparator2);

        quyenloi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/DanToc.png"))); // NOI18N
        quyenloi.setText("Quyền Lợi");
        quyenloi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quyenloiActionPerformed(evt);
            }
        });
        jdanhmuc.add(quyenloi);
        jdanhmuc.add(jSeparator3);

        ttcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/button6.Image.png"))); // NOI18N
        ttcn.setText("Thông Tin Cá Nhân");
        ttcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttcnActionPerformed(evt);
            }
        });
        jdanhmuc.add(ttcn);

        jMenuBar1.add(jdanhmuc);

        jquanly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/dangnhap.png"))); // NOI18N
        jquanly.setText("Quản Lý ");
        jquanly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jquanlyActionPerformed(evt);
            }
        });

        bangcong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/button5.Image.png"))); // NOI18N
        bangcong.setText("Bảng Công");
        bangcong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangcongActionPerformed(evt);
            }
        });
        jquanly.add(bangcong);
        jquanly.add(jSeparator6);

        jbophan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/QLNhanvien.png"))); // NOI18N
        jbophan.setText("Bộ Phận");
        jbophan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbophanActionPerformed(evt);
            }
        });
        jquanly.add(jbophan);
        jquanly.add(jSeparator7);

        jhoso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/button2.Image.gif"))); // NOI18N
        jhoso.setText("Hồ Sơ");
        jhoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhosoActionPerformed(evt);
            }
        });
        jquanly.add(jhoso);
        jquanly.add(jSeparator8);

        jphongban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/www.png"))); // NOI18N
        jphongban.setText("Phòng Ban");
        jphongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jphongbanActionPerformed(evt);
            }
        });
        jquanly.add(jphongban);

        jMenuBar1.add(jquanly);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/1269825271_system-help.png"))); // NOI18N
        jMenu5.setText("Chức Năng");

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/tim.png"))); // NOI18N
        jMenu2.setText("Tra Cứu");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/eee.png"))); // NOI18N
        jMenuItem4.setText("TT Cá Nhân");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator10);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/TinhLuong.png"))); // NOI18N
        jMenuItem5.setText("Lương");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenu5.add(jMenu2);

        danhgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/icon/eee.png"))); // NOI18N
        danhgia.setText("Xếp Loại NV");
        danhgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danhgiaActionPerformed(evt);
            }
        });
        jMenu5.add(danhgia);
        jMenu5.add(jSeparator9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jexitActionPerformed

    private void jdangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdangkyActionPerformed
        // TODO add your handling code here:
            DangKy a = new DangKy();
                 a.setLocationRelativeTo(null);
                 a.setVisible(true);
    }//GEN-LAST:event_jdangkyActionPerformed

    private void jnhansuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnhansuActionPerformed
        // TODO add your handling code here:
        NhanSu a = new NhanSu();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jnhansuActionPerformed

    private void quyenloiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quyenloiActionPerformed
        // TODO add your handling code here:
                 QuyenLoi a = new QuyenLoi();
                 a.setLocationRelativeTo(null);
                 a.setVisible(true);
    }//GEN-LAST:event_quyenloiActionPerformed

    private void bangcongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangcongActionPerformed
        // TODO add your handling code here:
                  BangCong a = new BangCong();
                 a.setLocationRelativeTo(null);
                 a.setVisible(true);
    }//GEN-LAST:event_bangcongActionPerformed

    private void txtluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtluongActionPerformed
        // TODO add your handling code here:
                 Luong Luong = new Luong();
                 Luong.setLocationRelativeTo(null);
                 Luong.setVisible(true);
        
    }//GEN-LAST:event_txtluongActionPerformed

    private void ttcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttcnActionPerformed
        // TODO add your handling code here:
                 ThongTinCaNhan a = new ThongTinCaNhan();
                 a.setLocationRelativeTo(null);
                 a.setVisible(true);
    }//GEN-LAST:event_ttcnActionPerformed

    private void jquanlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jquanlyActionPerformed
        // TODO add your handling code here:
                BangCong a = new BangCong();
                 a.setLocationRelativeTo(null);
                 a.setVisible(true);
                 
    }//GEN-LAST:event_jquanlyActionPerformed

    private void jbophanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbophanActionPerformed
        // TODO add your handling code here:
                   BoPhan a = new BoPhan();
                 a.setLocationRelativeTo(null);
                 a.setVisible(true);
    }//GEN-LAST:event_jbophanActionPerformed

    private void jhosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhosoActionPerformed
        // TODO add your handling code here:
                HoSo a = new HoSo();
                 a.setLocationRelativeTo(null);
                 a.setVisible(true);
    }//GEN-LAST:event_jhosoActionPerformed

    private void jphongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jphongbanActionPerformed
        // TODO add your handling code here:
                  PhongBan a = new PhongBan();
                 a.setLocationRelativeTo(null);
                 a.setVisible(true);
    }//GEN-LAST:event_jphongbanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DangNhap1 d1 = new DangNhap1(this,true);
        d1.setLocationRelativeTo(null);
        d1.setVisible(true);
        phanquyen();
                
//        TimKiem tk  = new TimKiem();
//               tk.setLocationRelativeTo(null);
//               tk.setVisible(true);
        
    }//GEN-LAST:event_formWindowOpened
    int i = 0 ;
    private void jluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jluongActionPerformed
        // TODO add your handling code here:
        i = 1;
    }//GEN-LAST:event_jluongActionPerformed

    private void jnhansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnhansActionPerformed
        // TODO add your handling code here:
        i = 2;
    }//GEN-LAST:event_jnhansActionPerformed

    private void jttnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttnhanvienActionPerformed
        // TODO add your handling code here:
        i = 3 ;
    }//GEN-LAST:event_jttnhanvienActionPerformed

    private void jhoso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhoso1ActionPerformed
        // TODO add your handling code here:
        i = 4;
    }//GEN-LAST:event_jhoso1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
            TimKiem tk  = new TimKiem();
            tk.setLocationRelativeTo(null);
            tk.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        timkiemluong tkl = new timkiemluong();
        tkl.setLocationRelativeTo(null);
        tkl.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
        if(i==1)
        {
             timkiemluong tkl = new timkiemluong();
             tkl.setLocationRelativeTo(null);
              tkl.setVisible(true);
    }                           
        
        if(i==2){
             NhanSu a = new NhanSu();
                a.setLocationRelativeTo(null);
                a.setVisible(true);
        }
        if(i == 3)
        {
              TimKiem tk  = new TimKiem();
                 tk.setLocationRelativeTo(null);
                tk.setVisible(true);
        }
        if(i == 4){
                    HoSo a = new HoSo();
                 a.setLocationRelativeTo(null);
                 a.setVisible(true);
        }
    }//GEN-LAST:event_txttimkiemActionPerformed

    private void danhgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danhgiaActionPerformed
        // TODO add your handling code here:
        DanhGia a = new DanhGia();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_danhgiaActionPerformed
 private void phanquyen()
 { 
     
     if(Share.nguoidangnhap.getQuyen().equals("Admin"))
     {
         
        
            txttimkiem.setEnabled(true);
         
     }
     else if (Share.nguoidangnhap.getQuyen().equals("users")) {
           jnhansu.setEnabled(false);
           jdangky.setEnabled(false);
           jquanly.setEnabled(false);
           jdanhmuc.setEnabled(false);
                   
        }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coban3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coban3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coban3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coban3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                coban3 cb = new coban3();
                cb.setLocationRelativeTo(null);
                cb.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bangcong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem danhgia;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem jbophan;
    private javax.swing.JMenuItem jdangky;
    private javax.swing.JMenuItem jdangnhap;
    private javax.swing.JMenu jdanhmuc;
    private javax.swing.JMenuItem jexit;
    private javax.swing.JMenuItem jhoso;
    private javax.swing.JRadioButton jhoso1;
    private javax.swing.JRadioButton jluong;
    private javax.swing.JRadioButton jnhans;
    private javax.swing.JMenuItem jnhansu;
    private javax.swing.JMenuItem jphongban;
    private javax.swing.JMenu jquanly;
    private javax.swing.JRadioButton jttnhanvien;
    private javax.swing.JMenuItem quyenloi;
    private javax.swing.JMenuItem ttcn;
    private javax.swing.JMenuItem txtluong;
    private javax.swing.JButton txttimkiem;
    // End of variables declaration//GEN-END:variables
}
