/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnss;

import ConnectToSql.Connect;
import MainMenu.MainMenu;
import MainMenu.MainMenu;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.security.MessageDigest;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import sun.invoke.empty.Empty;
import sun.java2d.pipe.SpanShapeRenderer;
import Models.Emp;       
import Models.MessageDialogHelper;
import Models.NguoiDung;
import Models.Share;
import Models.userDao;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {
Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2- getHeight()/2);
        
        conn = Connect.getDBConnect();
        
    }
     public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnlogin = new javax.swing.JButton();
        cmbquyen = new javax.swing.JComboBox<>();
        txtusername = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        aa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(null);

        btnlogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogin);
        btnlogin.setBounds(180, 190, 110, 25);

        cmbquyen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbquyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "user" }));
        jPanel2.add(cmbquyen);
        cmbquyen.setBounds(120, 150, 90, 23);

        txtusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtusername);
        txtusername.setBounds(120, 70, 170, 23);

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        jPanel2.add(txtpass);
        txtpass.setBounds(120, 110, 170, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Quyền:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 150, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mật Khẩu :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 110, 80, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên Đăng Nhập:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 70, 110, 17);

        aa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ConnectToSql/204193302_272400441320737_389822640111465452_n.jpg"))); // NOI18N
        aa.setText("jLabel4");
        jPanel2.add(aa);
        aa.setBounds(-10, 10, 960, 1360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
//        String sql ="select id ,username,password,phanquyen from [user] where (username=? and password=? and phanquyen=?)";
//        try {
//            int count = 0;
//            pst = conn.prepareStatement(sql);
//            
//            pst.setString(1,txtusername.getText());
//            pst.setString(2,getMD5(new String(txtpass.getPassword())));
//            pst.setString(3,cmbquyen.getSelectedItem().toString());
//            
//            rs = pst.executeQuery();
//            while(rs.next())
//            {   int id = rs.getInt(1);
//                Emp.empId = id;
//                String username = rs.getString("username");
//                
//            
//                count = count +1;
//            }
//            String access = (cmbquyen.getSelectedItem().toString());
//            if(access=="Admin")
//            { if(count == 1)
//                JOptionPane.showMessageDialog(null,"Đang Nhap Thanh Cong");
//                MainMenu menu = new MainMenu();
//                menu.setVisible(true);
//                this.dispose();
//                Date currentDate = GregorianCalendar.getInstance().getTime();
//                DateFormat df = DateFormat.getDateInstance();
//                String dateString = df.format(currentDate);
//                
//                Date d = new Date();
//                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
//                String timeString = sdf.format(d);
//                
//                String value0 = timeString;
//                String value1 = dateString;
//                
//                 int value = Emp.empId;
//                 String reg = "insert into audit (emp_id,date,status) values ('"+value+"','"+value0+" / "+value1+"','Logged in')";
//                 pst=conn.prepareStatement(reg);
//                 pst.execute();
//                 this.dispose();
//                
//                
//                
//               
//            }else
//            {
//                JOptionPane.showMessageDialog(null,"");
//            }         
//        } 
//        catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
//        finally
//        {
//            try {
//                rs.close();
//                pst.close();;
//                
//            } catch (Exception e) {
//                
//            }
//        }
       
             userDao dao = new userDao();
             
        try{
            NguoiDung nd = dao.checkloginDung(txtusername.getText(), getMD5(new String(txtpass.getPassword())));
           Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String dateString = df.format(currentDate);
                
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                String timeString = sdf.format(d);
                
                String value0 = timeString;
                String value1 = dateString;
                
                 int value = Emp.empId;
                 String reg = "insert into audit (emp_id,date,status) values ('"+value+"','"+value0+" / "+value1+"','Logged in')";
                 pst=conn.prepareStatement(reg);
                 pst.execute();
                 this.dispose();
            if(nd == null)
            {
                MessageDialogHelper.Showmesserror(this,"Ten dang nhap hoac mk sai","lổi");

            }
            else{
                Share.nguoidangnhap = nd ;
                 JOptionPane.showMessageDialog(null,"Đang Nhap Thanh Cong");
                MainMenu menu = new MainMenu();
                menu.setVisible(true);
                this.dispose();
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
            MessageDialogHelper.Showmesserror(this, e.getMessage(), "lỗi");
        }
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed
public String getMD5 (String md5)
{
    try {
        MessageDigest md = MessageDigest.getInstance("MD5");
        byte[] array = md.digest(md5.getBytes());
        
        StringBuffer sb = new StringBuffer();
        for(int i =0 ; i< array.length;i++)
        {
            sb.append(Integer.toHexString((array[i] & 0xFF)| 0x100).substring(1,3));
        }
        return sb.toString();
        
    } catch (Exception e) {
        e.printStackTrace();
    }
    return  null;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aa;
    private javax.swing.JButton btnlogin;
    private javax.swing.JComboBox<String> cmbquyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
